apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-flask-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "sample-flask-app.name" . }}
